### ISSUE TITLE
 Add important badges to the readme

### ISSUE THREAD

**Issue by henrykironde** [gvilitechltd/LibSWIFFT#10]
This makes it easy to navigate.

[![Documentation Status](https://readthedocs.org/projects/libswifft/badge/?version=latest)](http://libswifft.readthedocs.io/en/latest/?badge=latest)
[![package](https://github.com/gvilitechltd/libswifft/actions/workflows/new-code.yml/badge.svg?branch=main)](https://github.com/gvilitechltd/libswifft/actions/workflows/new-code.yml/)

**Comment by yarongvili1** [comment]
I believe the docs-badge should be:

[![Documentation Status](https://readthedocs.org/projects/libswifft/badge/?version=latest)](http://libswifft.readthedocs.io/en/latest/)
