### ISSUE TITLE
Installation issue on Ubuntu 20.02

### ISSUE THREAD

**Issue by jarrah42** [gvilitechltd/LibSWIFFT#17]
The installation instruction fail because a C++ compiler is not installed automatically. The line:

`sudo apt-get install g++`

should be added after `sudo apt-get install gcc` in the "Building LibSWIFFT" section.

**Comment by jarrah42** [comment]
In addition, when installing Catch2 from the Git repo, it defaults to the devel branch which is v3. This does not have a `catch.hpp` header, but uses `catch_all.hpp` instead, so the build fails. Either the branch needs to be changed to v2.x or the include needs to be changed to use `catch_all.hpp`.

**Comment by yarongvili1** [comment]
The instructions specify the specific versions of GCC, cmake and Catch2 that should be used, and with these versions the build works. Agreed that it would be helpful to replace the "normally installed" parts with step-by-step commands.
